name: Check Issue
on:
  issues:
    types:
      - opened
      - edited
      - assigned
jobs:
  check_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: pull in script
        uses: actions/checkout@4.2.2
        with:
          repository: IntegrationTesters/triage-scripts
      - name: install python
        uses: actions/setup-python@5.4.0 # v5.4.0
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: install python packages
        run: pip install -r requirements.txt
      - name: check and comment issue
        run: python3 main.py
        env:
          GH_TOKEN: ${{ secrets.TRIAGE_TOKEN }}
          GH_REPO: ${{ github.repository }}
          ISSUE: ${{ github.event.issue.number }}
