name: Check Issue
on:
  issues:
    types:
      - opened
jobs:
  check_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: pull in script
        uses: actions/checkout@latest
        with:
          repository: IntegrationTesters/triage-scripts
      - name: install python
        uses: actions/setup-python@latest # v5.4.0
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: install python packages
        run: pip install -r requirements.txt
      - name: check and comment issue
        run: python3 main.py
        env:
          GH_TOKEN: ${{ secrets.BOT_TOKEN }}
          GH_REPO: ${{ github.repository }}
          ISSUE: ${{ github.event.issue.number }}
